#!/usr/bin/env python3
"""
Add service account roles
Guide for adding necessary roles to service account
"""

def main():
    """Guide for adding service account roles"""
    
    print("🔧 Add Service Account Roles")
    print("=" * 50)
    print()
    print("✅ You're on the service account permissions page")
    print("❌ ISSUE: Service account needs proper roles to access calendars")
    print("✅ SOLUTION: Add the necessary roles")
    print()
    print("📋 STEP-BY-STEP SOLUTION:")
    print("=" * 30)
    print()
    print("🔧 STEP 1: Add Calendar API User Role")
    print("-" * 40)
    print("1. On the service account page, click 'Manage service account permissions'")
    print("2. Click 'Grant Access' or 'Add Principal'")
    print("3. In the 'New principals' field, add:")
    print("   idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print("4. In the 'Role' dropdown, search for and select:")
    print("   'Calendar API User'")
    print("5. Click 'Save'")
    print("6. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🔧 STEP 2: Alternative - Add via IAM Page")
    print("-" * 40)
    print("1. Go to 'IAM & Admin' > 'IAM' in the left sidebar")
    print("2. Find your service account in the list")
    print("3. Click the pencil icon to edit")
    print("4. Click 'Add Another Role'")
    print("5. Search for and select: 'Calendar API User'")
    print("6. Click 'Save'")
    print("7. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🔧 STEP 3: Additional Roles (if needed)")
    print("-" * 40)
    print("If 'Calendar API User' doesn't work, try these roles:")
    print("1. 'Service Account User'")
    print("2. 'Calendar API Editor'")
    print("3. 'Basic' (for basic Google API access)")
    print()
    print("🔧 STEP 4: Check API Access")
    print("-" * 40)
    print("1. Go to 'APIs & Services' > 'Library'")
    print("2. Search for 'Google Calendar API'")
    print("3. Make sure it's enabled")
    print("4. If not enabled, click 'Enable'")
    print("5. Wait 5-10 minutes for API to be enabled")
    print()
    print("🔧 STEP 5: Test on Remote Server")
    print("-" * 40)
    print("1. SSH into your remote server")
    print("2. Navigate to your project directory")
    print("3. Run: python diagnose_calendar.py")
    print("4. Should show: 'Found X accessible calendars'")
    print("5. Then run: python calendar_display_all_calendars.py tomorrow")
    print()
    print("🎯 QUICK LINKS:")
    print("-" * 20)
    print("• IAM & Admin: https://console.cloud.google.com/iam-admin/iam")
    print("• APIs & Services: https://console.cloud.google.com/apis/library")
    print("• Google Calendar: https://calendar.google.com")
    print()
    print("📧 Service Account Email:")
    print("   idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print()
    print("⚠️  IMPORTANT:")
    print("-" * 20)
    print("• Add the 'Calendar API User' role first")
    print("• Wait 10-15 minutes after adding roles")
    print("• Test with: python diagnose_calendar.py")
    print("• If still not working, try additional roles")
    print()
    print("✅ Expected Result:")
    print("   'Found X accessible calendars'")
    print("   Then: python calendar_display_all_calendars.py tomorrow")

if __name__ == '__main__':
    main()
