#!/usr/bin/env python3
"""
Alternative roles for service account
Guide for adding roles when Calendar API User is not available
"""

def main():
    """Alternative roles guide"""
    
    print("🔧 Alternative Service Account Roles")
    print("=" * 50)
    print()
    print("❌ ISSUE: 'Calendar API User' role not found")
    print("✅ SOLUTION: Try these alternative roles")
    print()
    print("📋 ALTERNATIVE ROLES TO TRY:")
    print("=" * 30)
    print()
    print("🔧 OPTION 1: Basic Roles")
    print("-" * 30)
    print("1. Go to: https://console.cloud.google.com/iam-admin/iam")
    print("2. Find your service account")
    print("3. Click the pencil icon to edit")
    print("4. Click 'Add Another Role'")
    print("5. Try these roles in order:")
    print("   • 'Basic'")
    print("   • 'Viewer'")
    print("   • 'Editor'")
    print("6. Click 'Save'")
    print("7. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🔧 OPTION 2: Service Account Roles")
    print("-" * 30)
    print("1. Go to: https://console.cloud.google.com/iam-admin/iam")
    print("2. Find your service account")
    print("3. Click the pencil icon to edit")
    print("4. Click 'Add Another Role'")
    print("5. Try these roles:")
    print("   • 'Service Account User'")
    print("   • 'Service Account Token Creator'")
    print("   • 'Service Account Key Admin'")
    print("6. Click 'Save'")
    print("7. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🔧 OPTION 3: Google Workspace Roles")
    print("-" * 30)
    print("1. Go to: https://console.cloud.google.com/iam-admin/iam")
    print("2. Find your service account")
    print("3. Click the pencil icon to edit")
    print("4. Click 'Add Another Role'")
    print("5. Try these roles:")
    print("   • 'Google Workspace Admin'")
    print("   • 'Google Workspace User'")
    print("   • 'Google Workspace Viewer'")
    print("6. Click 'Save'")
    print("7. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🔧 OPTION 4: Custom Roles")
    print("-" * 30)
    print("1. Go to: https://console.cloud.google.com/iam-admin/iam")
    print("2. Find your service account")
    print("3. Click the pencil icon to edit")
    print("4. Click 'Add Another Role'")
    print("5. Try these roles:")
    print("   • 'Custom'")
    print("   • 'Google API Client Library'")
    print("   • 'Google API Service Agent'")
    print("6. Click 'Save'")
    print("7. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🔧 OPTION 5: Project-Level Roles")
    print("-" * 30)
    print("1. Go to: https://console.cloud.google.com/iam-admin/iam")
    print("2. Find your service account")
    print("3. Click the pencil icon to edit")
    print("4. Click 'Add Another Role'")
    print("5. Try these roles:")
    print("   • 'Project Editor'")
    print("   • 'Project Viewer'")
    print("   • 'Project Owner'")
    print("6. Click 'Save'")
    print("7. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🔧 OPTION 6: API-Specific Roles")
    print("-" * 30)
    print("1. Go to: https://console.cloud.google.com/iam-admin/iam")
    print("2. Find your service account")
    print("3. Click the pencil icon to edit")
    print("4. Click 'Add Another Role'")
    print("5. Try these roles:")
    print("   • 'Google API Client Library'")
    print("   • 'Google API Service Agent'")
    print("   • 'Google API User'")
    print("6. Click 'Save'")
    print("7. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🧪 TEST AFTER EACH ROLE:")
    print("-" * 30)
    print("1. SSH into your remote server")
    print("2. Navigate to your project directory")
    print("3. Run: python diagnose_calendar.py")
    print("4. If you see 'Found X accessible calendars', you're done!")
    print("5. If still 0 calendars, try the next role")
    print()
    print("🎯 QUICK LINKS:")
    print("-" * 20)
    print("• IAM & Admin: https://console.cloud.google.com/iam-admin/iam")
    print("• Google Calendar API: https://console.cloud.google.com/apis/library/calendar-json.googleapis.com")
    print("• Calendar Settings: https://calendar.google.com/calendar/r/settings")
    print()
    print("📧 Service Account Email:")
    print("   idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print()
    print("⚠️  IMPORTANT:")
    print("-" * 20)
    print("• Try roles in order (Basic first)")
    print("• Wait 10-15 minutes after each role")
    print("• Test with: python diagnose_calendar.py")
    print("• If one role works, you're done!")
    print()
    print("✅ Expected Result:")
    print("   'Found X accessible calendars'")
    print("   Then: python calendar_display_all_calendars.py tomorrow")

if __name__ == '__main__':
    main()
