#!/usr/bin/env python3
"""
Complete setup guide for service account calendar access
Step-by-step solution for the calendar access issue
"""

import os
import json

def main():
    """Complete setup guide"""
    
    print("🔧 Complete Service Account Setup Guide")
    print("=" * 50)
    print()
    print("❌ ISSUE: Service account can't access your calendars")
    print("✅ SOLUTION: Complete setup process")
    print()
    print("📋 STEP-BY-STEP SOLUTION:")
    print("=" * 30)
    print()
    print("🔧 STEP 1: Create Service Account")
    print("-" * 40)
    print("1. Run: python calendar_service_account.py")
    print("2. Follow the instructions to create service account")
    print("3. Download the service-account.json file")
    print("4. Note the service account email address")
    print()
    print("🔧 STEP 2: Share Your Primary Calendar")
    print("-" * 40)
    print("1. Go to Google Calendar: https://calendar.google.com")
    print("2. Click the gear icon (Settings) in the top right")
    print("3. Click 'Settings' from the dropdown")
    print("4. In the left sidebar, click 'Settings for my calendars'")
    print("5. Click on your main calendar name")
    print("6. Click 'Share with specific people'")
    print("7. Click 'Add people'")
    print("8. Add the service account email (from step 1)")
    print("9. Set permission to 'See all event details'")
    print("10. Click 'Send'")
    print()
    print("🔧 STEP 3: Share Your Imported Calendar")
    print("-" * 40)
    print("1. In Google Calendar, find your imported calendar")
    print("2. Click the three dots next to the calendar name")
    print("3. Click 'Settings and sharing'")
    print("4. Click 'Share with specific people'")
    print("5. Click 'Add people'")
    print("6. Add the service account email")
    print("7. Set permission to 'See all event details'")
    print("8. Click 'Send'")
    print()
    print("🔧 STEP 4: Test Access")
    print("-" * 40)
    print("1. Wait 2-3 minutes for permissions to propagate")
    print("2. Run: python diagnose_calendar.py")
    print("3. You should see: 'Found X accessible calendars'")
    print("4. Then run: python calendar_display_all_calendars.py tomorrow")
    print()
    print("🎯 QUICK LINKS:")
    print("-" * 20)
    print("• Google Calendar: https://calendar.google.com")
    print("• Calendar Settings: https://calendar.google.com/calendar/r/settings")
    print("• Google Cloud Console: https://console.cloud.google.com")
    print()
    print("⚠️  IMPORTANT NOTES:")
    print("-" * 20)
    print("• You need to share EACH calendar individually")
    print("• The service account is like a separate Google account")
    print("• It needs explicit permission to access your calendars")
    print("• This is different from your personal Google account access")
    print()
    print("✅ After completing these steps:")
    print("   - Service account will access both calendars")
    print("   - Tomorrow's events will be found")
    print("   - iDotMatrix will display events from all calendars")
    print()
    print("🚀 START HERE:")
    print("   python calendar_service_account.py")

if __name__ == '__main__':
    main()
