#!/usr/bin/env python3
"""
Get service account JSON file
Guide to download the actual service-account.json file
"""

def main():
    """Guide to get service account JSON file"""
    
    print("🔧 Get Service Account JSON File")
    print("=" * 50)
    print()
    print("❌ ISSUE: You have OAuth files but no service-account.json")
    print("✅ SOLUTION: Download the actual service account JSON file")
    print()
    print("📋 STEP-BY-STEP SOLUTION:")
    print("=" * 30)
    print()
    print("🔧 STEP 1: Go to Google Cloud Console")
    print("-" * 40)
    print("1. Open: https://console.cloud.google.com")
    print("2. Select your project")
    print("3. Go to 'IAM & Admin' > 'Service Accounts'")
    print()
    print("🔧 STEP 2: Find Your Service Account")
    print("-" * 40)
    print("1. Look for a service account named something like:")
    print("   - 'iDotMatrix Calendar'")
    print("   - 'Calendar Service Account'")
    print("   - Or any service account you created")
    print("2. Click on the service account name")
    print()
    print("🔧 STEP 3: Create Service Account Key")
    print("-" * 40)
    print("1. Go to the 'Keys' tab")
    print("2. Click 'Add Key' > 'Create new key'")
    print("3. Choose 'JSON' format")
    print("4. Click 'Create'")
    print("5. A JSON file will download automatically")
    print()
    print("🔧 STEP 4: Rename and Place the File")
    print("-" * 40)
    print("1. The downloaded file will have a name like:")
    print("   - 'project-name-1234567890.json'")
    print("2. Rename it to 'service-account.json'")
    print("3. Place it in your project directory")
    print("4. Make sure it's in the same folder as your Python scripts")
    print()
    print("🔧 STEP 5: Test the Service Account")
    print("-" * 40)
    print("1. Run: python check_service_account_file.py")
    print("2. Should show: '✅ All required fields present'")
    print("3. Then run: python diagnose_calendar.py")
    print("4. Should show: 'Found X accessible calendars'")
    print()
    print("🎯 QUICK LINKS:")
    print("-" * 20)
    print("• Google Cloud Console: https://console.cloud.google.com")
    print("• IAM & Admin: https://console.cloud.google.com/iam-admin/serviceaccounts")
    print()
    print("⚠️  IMPORTANT:")
    print("-" * 20)
    print("• The service account JSON file is different from OAuth files")
    print("• It contains private keys and should be kept secure")
    print("• Don't share this file with anyone")
    print()
    print("✅ After getting the service-account.json file:")
    print("   - Share your calendar with the service account email")
    print("   - Set permission to 'See all event details'")
    print("   - Test with: python diagnose_calendar.py")

if __name__ == '__main__':
    main()
