#!/usr/bin/env python3
"""
Import ICS calendar guide
Step-by-step guide for importing ICS calendars into Google Calendar
"""

def main():
    """Import ICS calendar guide"""
    
    print("🔧 Import ICS Calendar Guide")
    print("=" * 50)
    print()
    print("✅ SOLUTION: Import ICS calendar into Google Calendar")
    print("📅 ICS URL: https://outlook.office365.com/owa/calendar/144d73fdf2654fb3b92983ee16e9d0b3@genpt.com/e829a99fc26b4c66a482420d04ea689513863417029725141930/calendar.ics")
    print()
    print("📋 STEP-BY-STEP SOLUTION:")
    print("=" * 30)
    print()
    print("🔧 STEP 1: Import ICS Calendar into Google Calendar")
    print("-" * 50)
    print("1. Go to: https://calendar.google.com")
    print("2. Click the gear icon (Settings) in the top right")
    print("3. Click 'Settings' from the dropdown")
    print("4. In the left sidebar, click 'Import & Export'")
    print("5. Click 'Import'")
    print("6. Choose 'From URL' option")
    print("7. Paste this URL:")
    print("   https://outlook.office365.com/owa/calendar/144d73fdf2654fb3b92983ee16e9d0b3@genpt.com/e829a99fc26b4c66a482420d04ea689513863417029725141930/calendar.ics")
    print("8. Click 'Import'")
    print("9. Wait for the import to complete")
    print()
    print("🔧 STEP 2: Share Imported Calendar with Service Account")
    print("-" * 50)
    print("1. In Google Calendar, find the imported calendar in the left sidebar")
    print("2. Click the three dots next to the calendar name")
    print("3. Click 'Settings and sharing'")
    print("4. Click 'Share with specific people'")
    print("5. Click 'Add people'")
    print("6. Add this email: idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print("7. Set permission to 'See all event details'")
    print("8. Click 'Send'")
    print("9. Wait 5-10 minutes for sharing to propagate")
    print()
    print("🔧 STEP 3: Test Service Account Access")
    print("-" * 50)
    print("1. SSH into your remote server")
    print("2. Navigate to your project directory")
    print("3. Run: python diagnose_calendar.py")
    print("4. Should show: 'Found X accessible calendars'")
    print("5. Then run: python calendar_display_all_calendars.py tomorrow")
    print()
    print("🔧 ALTERNATIVE: Direct ICS Import")
    print("-" * 50)
    print("If the URL import doesn't work, try:")
    print("1. Download the ICS file directly:")
    print("   wget 'https://outlook.office365.com/owa/calendar/144d73fdf2654fb3b92983ee16e9d0b3@genpt.com/e829a99fc26b4c66a482420d04ea689513863417029725141930/calendar.ics'")
    print("2. Go to Google Calendar > Settings > Import & Export")
    print("3. Click 'Select file from your computer'")
    print("4. Upload the downloaded .ics file")
    print("5. Click 'Import'")
    print("6. Wait for the import to complete")
    print()
    print("🔧 ALTERNATIVE: Subscribe to ICS Calendar")
    print("-" * 50)
    print("1. Go to: https://calendar.google.com")
    print("2. Click the '+' next to 'Other calendars'")
    print("3. Click 'From URL'")
    print("4. Paste the ICS URL:")
    print("   https://outlook.office365.com/owa/calendar/144d73fdf2654fb3b92983ee16e9d0b3@genpt.com/e829a99fc26b4c66a482420d04ea689513863417029725141930/calendar.ics")
    print("5. Click 'Add calendar'")
    print("6. Wait for the calendar to sync")
    print()
    print("🎯 QUICK LINKS:")
    print("-" * 20)
    print("• Google Calendar: https://calendar.google.com")
    print("• Import & Export: https://calendar.google.com/calendar/r/settings")
    print("• Calendar Settings: https://calendar.google.com/calendar/r/settings")
    print()
    print("📧 Service Account Email:")
    print("   idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print()
    print("⚠️  IMPORTANT:")
    print("-" * 20)
    print("• Import the ICS calendar first")
    print("• Then share it with the service account")
    print("• Wait 10-15 minutes for sharing to propagate")
    print("• Test with: python diagnose_calendar.py")
    print()
    print("✅ Expected Result:")
    print("   'Found X accessible calendars' (including the imported one)")
    print("   Then: python calendar_display_all_calendars.py tomorrow")

if __name__ == '__main__':
    main()
