#!/usr/bin/env python3
"""
Remote server troubleshooting guide
Comprehensive guide for troubleshooting service account on remote server
"""

def main():
    """Remote server troubleshooting guide"""
    
    print("🔍 Remote Server Service Account Troubleshooting")
    print("=" * 60)
    print()
    print("❌ ISSUE: Service account shows 0 calendars even though calendar is shared")
    print("✅ SOLUTION: Check common service account issues")
    print()
    print("📋 STEP-BY-STEP TROUBLESHOOTING:")
    print("=" * 40)
    print()
    print("🔧 STEP 1: Check Google Calendar API")
    print("-" * 40)
    print("1. Go to: https://console.cloud.google.com")
    print("2. Select your project: n8nwork-450415")
    print("3. Go to 'APIs & Services' > 'Library'")
    print("4. Search for 'Google Calendar API'")
    print("5. Click on 'Google Calendar API'")
    print("6. If not enabled, click 'Enable'")
    print("7. Wait 5-10 minutes for API to be enabled")
    print()
    print("🔧 STEP 2: Check Service Account Permissions")
    print("-" * 40)
    print("1. Go to: https://console.cloud.google.com")
    print("2. Go to 'IAM & Admin' > 'IAM'")
    print("3. Find your service account: idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print("4. Click the pencil icon to edit")
    print("5. Add role: 'Calendar API User'")
    print("6. Click 'Save'")
    print("7. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🔧 STEP 3: Re-share Calendar")
    print("-" * 40)
    print("1. Go to: https://calendar.google.com")
    print("2. Click gear icon > Settings")
    print("3. Go to 'Settings for my calendars'")
    print("4. Click on your calendar name")
    print("5. Click 'Share with specific people'")
    print("6. Remove the service account if it exists")
    print("7. Add it back: idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print("8. Set permission to 'See all event details'")
    print("9. Click 'Send'")
    print("10. Wait 5-10 minutes for sharing to propagate")
    print()
    print("🔧 STEP 4: Test on Remote Server")
    print("-" * 40)
    print("1. SSH into your remote server")
    print("2. Navigate to your project directory")
    print("3. Run: python diagnose_calendar.py")
    print("4. Should show: 'Found X accessible calendars'")
    print("5. If still 0 calendars, try:")
    print("   - python troubleshoot_service_account.py")
    print("   - Check the detailed error messages")
    print()
    print("🔧 STEP 5: Alternative Solutions")
    print("-" * 40)
    print("If still not working, try:")
    print("1. Create a new service account key:")
    print("   - Delete the current service-account.json")
    print("   - Create a new key in Google Cloud Console")
    print("   - Download the new JSON file")
    print("   - Share calendar with the new service account email")
    print()
    print("2. Check if the service account has domain-wide delegation:")
    print("   - Go to Service Accounts in Google Cloud Console")
    print("   - Click on your service account")
    print("   - Check 'Domain-wide delegation' section")
    print("   - This might be needed for some calendar access")
    print()
    print("3. Try using a different calendar:")
    print("   - Create a test calendar")
    print("   - Share it with the service account")
    print("   - Test if the service account can access it")
    print()
    print("🎯 QUICK LINKS:")
    print("-" * 20)
    print("• Google Cloud Console: https://console.cloud.google.com")
    print("• APIs & Services: https://console.cloud.google.com/apis/library")
    print("• IAM & Admin: https://console.cloud.google.com/iam-admin/iam")
    print("• Google Calendar: https://calendar.google.com")
    print()
    print("📧 Service Account Email:")
    print("   idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print()
    print("⏳ IMPORTANT: Wait 10-15 minutes after making changes")
    print("Then test with: python diagnose_calendar.py")
    print()
    print("✅ Expected Result:")
    print("   'Found X accessible calendars'")
    print("   Then: python calendar_display_all_calendars.py tomorrow")

if __name__ == '__main__':
    main()
