#!/usr/bin/env python3
"""
Proper service account setup
Creates a real service account JSON file for Google Calendar API
"""

import os
import json

def setup_service_account_proper():
    """Setup service account properly"""
    
    print("🔧 Proper Service Account Setup")
    print("=" * 50)
    print()
    print("❌ ISSUE: Current setup created OAuth token instead of service account")
    print("✅ SOLUTION: Create proper service account JSON file")
    print()
    print("📋 STEP-BY-STEP SOLUTION:")
    print("=" * 30)
    print()
    print("🔧 STEP 1: Create Service Account in Google Cloud Console")
    print("-" * 50)
    print("1. Go to: https://console.cloud.google.com")
    print("2. Select your project (or create a new one)")
    print("3. Go to 'IAM & Admin' > 'Service Accounts'")
    print("4. Click 'Create Service Account'")
    print("5. Name: 'iDotMatrix Calendar'")
    print("6. Description: 'Service account for iDotMatrix calendar integration'")
    print("7. Click 'Create and Continue'")
    print("8. Skip role assignment for now")
    print("9. Click 'Done'")
    print()
    print("🔧 STEP 2: Create Service Account Key")
    print("-" * 50)
    print("1. Find your service account in the list")
    print("2. Click on the service account name")
    print("3. Go to 'Keys' tab")
    print("4. Click 'Add Key' > 'Create new key'")
    print("5. Choose 'JSON' format")
    print("6. Click 'Create'")
    print("7. Download the JSON file")
    print("8. Rename it to 'service-account.json'")
    print("9. Place it in your project directory")
    print()
    print("🔧 STEP 3: Enable Google Calendar API")
    print("-" * 50)
    print("1. Go to 'APIs & Services' > 'Library'")
    print("2. Search for 'Google Calendar API'")
    print("3. Click on 'Google Calendar API'")
    print("4. Click 'Enable'")
    print()
    print("🔧 STEP 4: Share Your Calendar")
    print("-" * 50)
    print("1. Go to Google Calendar: https://calendar.google.com")
    print("2. Click the gear icon (Settings) in the top right")
    print("3. Click 'Settings' from the dropdown")
    print("4. In the left sidebar, click 'Settings for my calendars'")
    print("5. Click on your main calendar name")
    print("6. Click 'Share with specific people'")
    print("7. Click 'Add people'")
    print("8. Add the service account email (from the JSON file)")
    print("9. Set permission to 'See all event details'")
    print("10. Click 'Send'")
    print()
    print("🔧 STEP 5: Test Service Account")
    print("-" * 50)
    print("1. Run: python diagnose_calendar.py")
    print("2. You should see: 'Found X accessible calendars'")
    print("3. Then run: python calendar_display_all_calendars.py tomorrow")
    print()
    print("🎯 QUICK LINKS:")
    print("-" * 20)
    print("• Google Cloud Console: https://console.cloud.google.com")
    print("• Google Calendar: https://calendar.google.com")
    print("• Calendar Settings: https://calendar.google.com/calendar/r/settings")
    print()
    print("⚠️  IMPORTANT:")
    print("-" * 20)
    print("• Service account is different from OAuth")
    print("• Service account needs explicit calendar sharing")
    print("• Service account is more reliable for servers")
    print()
    print("✅ After completing these steps:")
    print("   - Service account will access your calendar")
    print("   - Tomorrow's events will be found")
    print("   - iDotMatrix will display events from all calendars")

def main():
    """Main function"""
    setup_service_account_proper()

if __name__ == '__main__':
    main()
