#!/usr/bin/env python3
"""
Share calendar with service account
Guide to share your calendar with the service account
"""

def main():
    """Guide to share calendar with service account"""
    
    print("🔧 Share Calendar with Service Account")
    print("=" * 50)
    print()
    print("✅ Service account found: idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print("❌ ISSUE: Calendar not shared with service account yet")
    print("✅ SOLUTION: Share your calendar with the service account")
    print()
    print("📋 STEP-BY-STEP SOLUTION:")
    print("=" * 30)
    print()
    print("🔧 STEP 1: Go to Google Calendar")
    print("-" * 40)
    print("1. Open: https://calendar.google.com")
    print("2. Click the gear icon (Settings) in the top right")
    print("3. Click 'Settings' from the dropdown")
    print()
    print("🔧 STEP 2: Share Your Main Calendar")
    print("-" * 40)
    print("1. In the left sidebar, click 'Settings for my calendars'")
    print("2. Click on your main calendar name")
    print("3. Click 'Share with specific people'")
    print("4. Click 'Add people'")
    print("5. Add this email: idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print("6. Set permission to 'See all event details'")
    print("7. Click 'Send'")
    print()
    print("🔧 STEP 3: Share Your Imported Calendar (if needed)")
    print("-" * 40)
    print("1. Find your imported calendar in the left sidebar")
    print("2. Click the three dots next to the calendar name")
    print("3. Click 'Settings and sharing'")
    print("4. Click 'Share with specific people'")
    print("5. Click 'Add people'")
    print("6. Add this email: idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print("7. Set permission to 'See all event details'")
    print("8. Click 'Send'")
    print()
    print("🔧 STEP 4: Test Access")
    print("-" * 40)
    print("1. Wait 2-3 minutes for permissions to propagate")
    print("2. Run: python diagnose_calendar.py")
    print("3. You should see: 'Found X accessible calendars'")
    print("4. Then run: python calendar_display_all_calendars.py tomorrow")
    print()
    print("🎯 QUICK LINKS:")
    print("-" * 20)
    print("• Google Calendar: https://calendar.google.com")
    print("• Calendar Settings: https://calendar.google.com/calendar/r/settings")
    print()
    print("⚠️  IMPORTANT:")
    print("-" * 20)
    print("• The service account is like a separate Google account")
    print("• It needs explicit permission to access your calendars")
    print("• You need to share each calendar individually")
    print()
    print("✅ After sharing:")
    print("   - Service account will access your calendars")
    print("   - Tomorrow's events will be found")
    print("   - iDotMatrix will display events from all calendars")
    print()
    print("📧 Service Account Email to Share With:")
    print("   idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")

if __name__ == '__main__':
    main()
