#!/usr/bin/env python3
"""
Simple setup guide - focus on getting service account working
Step-by-step solution for service account calendar access
"""

def main():
    """Simple setup guide"""
    
    print("🔧 Simple Service Account Setup")
    print("=" * 40)
    print()
    print("❌ ISSUE: No service account file found")
    print("✅ SOLUTION: Create service account first")
    print()
    print("📋 STEP-BY-STEP SOLUTION:")
    print("=" * 30)
    print()
    print("🔧 STEP 1: Create Service Account")
    print("-" * 40)
    print("1. Run: python calendar_service_account.py")
    print("2. Follow the instructions to create service account")
    print("3. Download the service-account.json file")
    print("4. Note the service account email address")
    print()
    print("🔧 STEP 2: Share Your Main Calendar")
    print("-" * 40)
    print("1. Go to Google Calendar: https://calendar.google.com")
    print("2. Click the gear icon (Settings) in the top right")
    print("3. Click 'Settings' from the dropdown")
    print("4. In the left sidebar, click 'Settings for my calendars'")
    print("5. Click on your main calendar name")
    print("6. Click 'Share with specific people'")
    print("7. Click 'Add people'")
    print("8. Add the service account email (from step 1)")
    print("9. Set permission to 'See all event details'")
    print("10. Click 'Send'")
    print()
    print("🔧 STEP 3: Test Access")
    print("-" * 40)
    print("1. Wait 2-3 minutes for permissions to propagate")
    print("2. Run: python diagnose_calendar.py")
    print("3. You should see: 'Found X accessible calendars'")
    print("4. Then run: python calendar_display_all_calendars.py tomorrow")
    print()
    print("🎯 QUICK LINKS:")
    print("-" * 20)
    print("• Google Calendar: https://calendar.google.com")
    print("• Calendar Settings: https://calendar.google.com/calendar/r/settings")
    print("• Google Cloud Console: https://console.cloud.google.com")
    print()
    print("⚠️  IMPORTANT:")
    print("-" * 20)
    print("• You need to share your calendar with the service account")
    print("• The service account is like a separate Google account")
    print("• It needs explicit permission to access your calendars")
    print()
    print("✅ After completing these steps:")
    print("   - Service account will access your calendar")
    print("   - Tomorrow's events will be found")
    print("   - iDotMatrix will display events")
    print()
    print("🚀 START HERE:")
    print("   python calendar_service_account.py")

if __name__ == '__main__':
    main()
