#!/usr/bin/env python3
"""
Visual setup guide with direct links
Step-by-step guide with exact links for service account setup
"""

def main():
    """Visual setup guide with direct links"""
    
    print("🔧 Visual Service Account Setup Guide")
    print("=" * 60)
    print()
    print("📋 STEP-BY-STEP WITH DIRECT LINKS:")
    print("=" * 40)
    print()
    print("🔧 STEP 1: Add Calendar API User Role")
    print("-" * 50)
    print("1. Click this link: https://console.cloud.google.com/iam-admin/iam")
    print("2. Find your service account in the list:")
    print("   idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print("3. Click the pencil icon (edit) next to your service account")
    print("4. Click 'Add Another Role'")
    print("5. In the role dropdown, search for: 'Calendar API User'")
    print("6. Select 'Calendar API User'")
    print("7. Click 'Save'")
    print("8. Wait 5-10 minutes for permissions to propagate")
    print()
    print("🔧 STEP 2: Enable Google Calendar API")
    print("-" * 50)
    print("1. Click this link: https://console.cloud.google.com/apis/library/calendar-json.googleapis.com")
    print("2. If you see 'Enable' button, click it")
    print("3. If you see 'Manage' button, the API is already enabled")
    print("4. Wait 5-10 minutes for API to be enabled")
    print()
    print("🔧 STEP 3: Share Calendar with Service Account")
    print("-" * 50)
    print("1. Click this link: https://calendar.google.com/calendar/r/settings")
    print("2. In the left sidebar, click 'Settings for my calendars'")
    print("3. Click on your main calendar name")
    print("4. Click 'Share with specific people'")
    print("5. Click 'Add people'")
    print("6. Add this email: idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print("7. Set permission to 'See all event details'")
    print("8. Click 'Send'")
    print("9. Wait 5-10 minutes for sharing to propagate")
    print()
    print("🔧 STEP 4: Test on Remote Server")
    print("-" * 50)
    print("1. SSH into your remote server")
    print("2. Navigate to your project directory")
    print("3. Run: python diagnose_calendar.py")
    print("4. Should show: 'Found X accessible calendars'")
    print("5. Then run: python calendar_display_all_calendars.py tomorrow")
    print()
    print("🎯 DIRECT LINKS:")
    print("=" * 20)
    print("• IAM & Admin: https://console.cloud.google.com/iam-admin/iam")
    print("• Google Calendar API: https://console.cloud.google.com/apis/library/calendar-json.googleapis.com")
    print("• Calendar Settings: https://calendar.google.com/calendar/r/settings")
    print()
    print("📧 Service Account Email:")
    print("   idotmatrix-service-account@n8nwork-450415.iam.gserviceaccount.com")
    print()
    print("⚠️  IMPORTANT:")
    print("-" * 20)
    print("• Follow the steps in order")
    print("• Wait 10-15 minutes after each step")
    print("• Test with: python diagnose_calendar.py")
    print("• If still not working, try additional roles")
    print()
    print("✅ Expected Result:")
    print("   'Found X accessible calendars'")
    print("   Then: python calendar_display_all_calendars.py tomorrow")

if __name__ == '__main__':
    main()
